server:
   port: 8092
spring:
  application:    name: person-detil-service
  datasource:
    url: jdbc:oracle:thin:@DESKTOP-C4G4QQ6:1521/XEPDB1
    username: springuser
    password: springuser
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
eureka:
   client:
      serviceUrl:
          defaultZone: http://localhost:8761/eureka
management:  health:    circuitbreakers:      enabled: true
  endpoints:    web:      exposure:        include: health
  endpoint:    health:      show-details: always
resilience4j:  circuitbreaker:    instances:
      personDetailService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED                                                  